version: '3.8'
services:
  spark:
    container_name: spark
    build: .
    command: tail -F anything
    image: pnthrleo/spark-template:latest
    ports:
      - "4040:4040"
      - "8888:8888"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./output:/app/output
      - ./data_mart:/app/data_mart
    networks:
      - proxy
    environment:
      - DB_ADRESS=database:1433
      - DB_IP=database
      - DB_PORT=1433
      - DB_DATABASE=kmeans
      - DB_USERNAME=sa
      - DB_PASSWORD=gig@chad_gigAchad0vich
networks:
  proxy:
    name: proxy-net
    external: true
